spring:
  datasource:
    url: jdbc:mysql://localhost/paprojecttest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
    username: pa
    password: pa
    hikari:
      maximum-pool-size: 1
